// src/config/brand.ts
export const brand = {
  name: "Int Town Services",
  tagline: "Boston's Trusted Towing Service",
  est: "EST. 2010",
  instagram: "@INTTOWNSERVICES",
  phoneDisplay: "617 555 TOW",
  phoneE164: "+16175558696",
  website: "www.inttownservices.com",
  email: "info@inttownservices.com",
  address: "Boston, MA",
  mapsQuery: "Int Town Services Boston MA",
  contactSubtitle: "24/7 Emergency Towing Service in Boston. Fast, Reliable, Professional.",
  hours: [
    "Emergency Towing: 24/7",
    "Office Hours: Mon-Fri, 8:00 AM to 6:00 PM",
    "Saturday: 9:00 AM to 4:00 PM",
    "Sunday: Emergency Service Only",
  ],

  ctas: {
    primary: "Emergency Towing",
    secondary: "Roadside Assistance",
  },

  services: [
    "Emergency Towing",
    "Roadside Assistance",
    "Flatbed Towing",
    "Heavy Duty Towing",
    "Motorcycle Towing",
    "Accident Recovery",
    "Jump Start Service",
    "Tire Change Service",
    "Lockout Service",
    "Fuel Delivery",
    "Winch Out Service",
    "Long Distance Towing",
    "Interstate Transport",
    "Vehicle Storage",
    "Insurance Towing",
  ],

  theme: {
    bg: "#ffffff",
    accent: "#0066cc", // Blue for trust and professionalism
    secondary: "#003d7a", // Darker blue
    text: "#1a1a1a",
    muted: "rgba(0,0,0,.6)",
    border: "rgba(0,102,204,.2)",
  },
  // ✅ Agrega en src/config/brand.js
about: {
  heroTitle: "About Int Town Services",
  heroSubtitle:
    "Boston's premier 24/7 towing service — fast response times, professional service, and reliable assistance when you need it most.",
  storyTitle: "Our Story",
  storyP1:
    "Int Town Services has been serving Boston and surrounding areas since 2010, providing reliable emergency towing and roadside assistance. We understand that breakdowns and accidents happen at the worst times, which is why we're available 24/7.",
  storyP2:
    "Our fleet of modern tow trucks and experienced operators ensure your vehicle is handled with care and professionalism. From emergency towing to roadside assistance, we're here to get you back on the road safely and quickly.",
  mission:
    "Provide fast, reliable, and professional towing services with 24/7 availability, ensuring our customers receive prompt assistance when they need it most.",
  vision:
    "Be Boston's most trusted towing service, known for rapid response times, professional service, and commitment to customer safety and satisfaction.",
  values:
    "Fast response, reliability, professionalism, safety, and treating every customer with respect and care during stressful situations.",
},
team: [
  {
    name: "Towing Operators",
    role: "Professional Tow Truck Drivers",
    description:
      "Licensed and experienced operators trained in safe vehicle recovery, handling all types of vehicles with care and precision.",
  },
  {
    name: "Dispatch Team",
    role: "24/7 Emergency Response",
    description:
      "Our dispatch team coordinates rapid response times, ensuring help arrives quickly when you need it most.",
  },
  {
    name: "Roadside Assistance Specialists",
    role: "On-Site Service Experts",
    description:
      "Trained professionals ready to handle jump starts, tire changes, lockouts, and other roadside emergencies.",
  },
],
serviceCards: [
  {
    title: "Emergency Towing",
    description: "24/7 emergency towing service throughout Boston. Fast response times, professional operators, and safe vehicle transport.",
    features: ["24/7 availability", "Average 15-30 minute response", "All vehicle types", "Professional operators"],
    availability: "24/7 Available",
  },
  {
    title: "Roadside Assistance",
    description: "Comprehensive roadside assistance for breakdowns, flat tires, dead batteries, and lockouts. We come to you, fast.",
    features: ["Jump start service", "Tire changes", "Lockout service", "Fuel delivery"],
    availability: "24/7 Available",
  },
  {
    title: "Flatbed Towing",
    description: "Safe flatbed towing for luxury vehicles, low-riding cars, and vehicles that require extra care during transport.",
    features: ["All-wheel drive safe", "Luxury vehicle handling", "No damage guarantee", "Professional equipment"],
    availability: "Available",
  },
  {
    title: "Heavy Duty Towing",
    description: "Heavy-duty towing for trucks, buses, RVs, and commercial vehicles. Specialized equipment for large vehicles.",
    features: ["Commercial vehicles", "RVs and campers", "Trucks and buses", "Specialized equipment"],
    availability: "Available",
  },
  {
    title: "Motorcycle Towing",
    description: "Specialized motorcycle towing with proper equipment to ensure your bike arrives safely without damage.",
    features: ["Motorcycle-specific equipment", "Secure transport", "Experienced handlers", "Damage-free guarantee"],
    availability: "Available",
  },
  {
    title: "Accident Recovery",
    description: "Professional accident recovery service. We work with police and insurance companies to safely recover vehicles from accident scenes.",
    features: ["Police coordination", "Insurance assistance", "Safe recovery", "24/7 availability"],
    availability: "24/7 Available",
  },
  {
    title: "Jump Start Service",
    description: "Dead battery? We'll come to your location and get you back on the road quickly with professional jump start service.",
    features: ["Fast response", "All vehicle types", "Battery testing available", "24/7 service"],
    availability: "24/7 Available",
  },
  {
    title: "Tire Change Service",
    description: "Flat tire? Our roadside assistance team will come to you and change your tire safely and quickly.",
    features: ["On-site service", "All tire sizes", "Spare tire installation", "Professional service"],
    availability: "24/7 Available",
  },
  {
    title: "Lockout Service",
    description: "Locked out of your vehicle? We can help you get back in quickly without damaging your vehicle.",
    features: ["Non-destructive entry", "Fast response", "All vehicle types", "Professional locksmith techniques"],
    availability: "24/7 Available",
  },
  {
    title: "Fuel Delivery",
    description: "Ran out of gas? We'll deliver fuel to your location so you can get back on the road without leaving your vehicle.",
    features: ["Fast delivery", "Regular and premium fuel", "Convenient service", "24/7 availability"],
    availability: "24/7 Available",
  },
  {
    title: "Winch Out Service",
    description: "Stuck in mud, snow, or a ditch? Our winch-out service can recover your vehicle from difficult situations.",
    features: ["Off-road recovery", "Snow recovery", "Mud recovery", "Professional equipment"],
    availability: "Available",
  },
  {
    title: "Long Distance Towing",
    description: "Need to transport your vehicle long distance? We provide reliable long-distance towing throughout New England and beyond.",
    features: ["Interstate transport", "Secure transport", "Professional drivers", "Competitive rates"],
    availability: "Available",
  },
  {
    title: "Interstate Transport",
    description: "Professional vehicle transport service for moving vehicles across state lines safely and efficiently.",
    features: ["Multi-state transport", "Secure handling", "Timely delivery", "Insurance coverage"],
    availability: "Available",
  },
  {
    title: "Vehicle Storage",
    description: "Secure vehicle storage facility for short-term or long-term storage needs. Climate-controlled options available.",
    features: ["Secure facility", "Short and long-term", "Climate-controlled options", "Insurance accepted"],
    availability: "Available",
  },
  {
    title: "Insurance Towing",
    description: "We work directly with insurance companies to provide towing services for accident and breakdown claims.",
    features: ["Direct insurance billing", "Claim coordination", "Fast processing", "Professional service"],
    availability: "24/7 Available",
  },
],
serviceCategories: {
  emergency: [
    "Emergency Towing",
    "Roadside Assistance",
    "Accident Recovery",
    "Jump Start Service",
    "Tire Change Service",
    "Lockout Service",
    "Fuel Delivery",
    "Insurance Towing",
  ],
  specialized: [
    "Flatbed Towing",
    "Heavy Duty Towing",
    "Motorcycle Towing",
    "Winch Out Service",
    "Long Distance Towing",
    "Interstate Transport",
    "Vehicle Storage",
  ],
},
processSteps: [
  { step: "01", title: "Call for help", description: "Call our 24/7 hotline or use our online form. We'll get your location and dispatch help immediately." },
  { step: "02", title: "Fast dispatch", description: "Our dispatch team sends the nearest available truck to your location within minutes." },
  { step: "03", title: "Professional service", description: "Our trained operator arrives and handles your vehicle with care and professionalism." },
  { step: "04", title: "Safe delivery", description: "Your vehicle is safely transported to your destination or repair shop." },
],
// ✅ Agrega en src/config/brand.js
galleryCategories: [
  "All",
  "Emergency Towing",
  "Roadside Assistance",
  "Heavy Duty",
  "Accident Recovery",
  "Motorcycle",
  "Flatbed",
  "Long Distance",
],
galleryProjects: [
  // ✅ BEFORE / AFTER (2 fotos reales)
  {
    id: "ba-1",
    title: "Before / After",
    description: "Body work + paint refinishing.",
    category: "Collision Repair",
    client: "Customer Vehicle",
    status: "Completed",
    year: "2025",
    highlights: ["Free estimate", "Paint match", "Quality finish"],
    beforeImage: "/gallery/Lancer-before.jpeg",
    afterImage: "/gallery/Lancer-after.jpeg",
    link: "",
  },
  {
    id: "ba-2",
    title: "Painting Process",
    description: "Prep & refinishing process.",
    category: "Paint",
    client: "Customer Vehicle",
    status: "Completed",
    year: "2025",
    highlights: ["Prep", "Paint", "Clear coat", "Finish check"],
    beforeImage: "/gallery/painting-after.jpeg",
    afterImage: "/gallery/painting-before.jpeg",
    link: "",
  },

  // ✅ SINGLE (1 foto)
  {
    id: "s-1",
    title: "Alignment and balancing",
    description: "Shop work showcase.",
    category: "Alignment and balancing",
    client: "Customer Vehicle",
    status: "Completed",
    year: "2025",
    highlights: ["Clean finish", "Inspection", "Ready for pickup"],
    image: "/gallery/Civic.jpeg",
    link: "",
  },
  {
    id: "s-2",
    title: "Routine inspection",
    description: "Inspection",
    category: "Frame",
    client: "Customer Vehicle",
    status: "Completed",
    year: "2025",
    highlights: ["Structural checks", "Alignment", "Quality control"],
    image: "/gallery/Jeep.jpeg",
    link: "",
  },
  {
    id: "s-3",
    title: "Detailing services",
    description: "Shop work showcase.",
    category: "Collision Repair",
    client: "Customer Vehicle",
    status: "Completed",
    year: "2025",
    highlights: ["Body work", "Paint match", "Final detailing"],
    image: "/gallery/Toyota.jpeg",
    link: "",
  },

  // ✅ NUEVAS (SINGLE) — como pediste (NO before/after)
  {
    id: "s-trans-1",
    title: "Transmission Replacement",
    description: "Transmission replacement and road-ready testing.",
    category: "Transmission",
    status: "Completed",
    client: "Customer Vehicle",
    year: "2025",
    highlights: ["Removal & install", "Fluid service", "Road test"],
    image: "/gallery/Transmission.jpeg",
    link: "",
  },
  {
    id: "s-engine-1",
    title: "Engine Replacement",
    description: "Engine replacement with full inspection and verification.",
    category: "Engine",
    status: "Completed",
    client: "Customer Vehicle",
    year: "2025",
    highlights: ["Swap & mounts", "Fluids & filters", "Final inspection"],
    image: "/gallery/Engine.jpeg",
    link: "",
  },
  {
    id: "s-elec-1",
    title: "Electrical Diagnostics",
    description: "Electrical diagnostics and repairs for reliable performance.",
    category: "Electrical",
    status: "Completed",
    client: "Customer Vehicle",
    year: "2025",
    highlights: ["Scan & testing", "Wiring checks", "Fault resolution"],
    image: "/gallery/Electrical.jpeg",
    link: "",
  },
  {
    id: "s-oil-1",
    title: "Oil Change Service",
    description: "Oil and filter change with quick multi-point inspection.",
    category: "Maintenance",
    status: "Completed",
    client: "Customer Vehicle",
    year: "2025",
    highlights: ["Oil + filter", "Fluid top-off", "Quick inspection"],
    image: "/gallery/Oil.jpeg",
    link: "",
  },
],


galleryStats: [
  { number: "15-30", label: "Min Response Time" },
  { number: "24/7", label: "Emergency Service" },
  { number: "1000+", label: "Happy Customers" },
  { number: "⭐ 4.9", label: "Customer Rating" },
],

};
